### ISSUE TITLE
TexLive 2018 issue on Travis

### ISSUE THREAD

**Issue by guilgautier** [CRIStAL-Sigma/mock_tex_paper#1]
Hi guys,

I wanted to reuse the LaTex paper template and restarted last Travis build.
I got an issue with downloading/installing TexLive 2018 see [Travis build](https://travis-ci.org/CRIStAL-Sigma/mock_tex_paper/builds/311420295)

Somebody seems to have had the same kind of issues on [StackExchange](https://tex.stackexchange.com/a/398831) the last section of the answer looks similar to what we are currently doing.

@guillep if you have time to have a look that would be nice :)

Cheers

**Comment by guilgautier** [comment]
Actually, @rbardenet had already raised the issue https://github.com/CRIStAL-Sigma/latex-travis-test/issues/1
Sorry for the doublon @guillep!

**Comment by guillep** [comment]
I'll for sure fix it tomorrow morning ^^

**Comment by guillep** [comment]
I've pushed a fix in both repositories.

This build went already green: https://travis-ci.org/CRIStAL-Sigma/latex-travis-test/builds/406134003

The other is running so far, but given it's the same config, I hope it will have the same result ^^.
https://travis-ci.org/CRIStAL-Sigma/mock_tex_paper/builds/406148760

**Comment by guillep** [comment]
Build green!
